In [1]:
import numpy as np
import pandas as pd

In [2]:
df_training = pd.read_csv("../data_mod/train_motion_data.csv")
df_test = pd.read_csv("../data_mod/test_motion_data.csv")

df_training

          AccX      AccY   Class  DiffAccX  DiffAccY
0     0.000000  0.000000  NORMAL  0.000000  0.000000
1    -1.624864 -1.082492  NORMAL -1.624864 -1.082492
2    -0.594660 -0.122410  NORMAL  1.030204  0.960082
3     0.738478 -0.228456  NORMAL  1.333138 -0.106046
4     0.101741  0.777568  NORMAL -0.636737  1.006023
...        ...       ...     ...       ...       ...
3411  0.915688 -2.017489    SLOW  2.374675 -1.824629
3412 -1.934203  0.914925    SLOW -2.849891  2.932414
3413 -0.222845  0.747304    SLOW  1.711359 -0.167621
3414 -0.349423  0.067261    SLOW -0.126579 -0.680043
3415 -0.402428  0.406218    SLOW -0.053005  0.338957

[3416 rows x 5 columns]

In [3]:
df_training.isna().sum()

AccX        0
AccY        0
Class       0
DiffAccX    0
DiffAccY    0
dtype: int64

In [4]:
df_training = df_training.replace(
    {"Class": {"NORMAL": 0, "AGGRESSIVE": 1, "SLOW": 2}})
df_test = df_test.replace(
    {"Class": {"NORMAL": 0, "AGGRESSIVE": 1, "SLOW": 2}})
df_training

          AccX      AccY  Class  DiffAccX  DiffAccY
0     0.000000  0.000000      0  0.000000  0.000000
1    -1.624864 -1.082492      0 -1.624864 -1.082492
2    -0.594660 -0.122410      0  1.030204  0.960082
3     0.738478 -0.228456      0  1.333138 -0.106046
4     0.101741  0.777568      0 -0.636737  1.006023
...        ...       ...    ...       ...       ...
3411  0.915688 -2.017489      2  2.374675 -1.824629
3412 -1.934203  0.914925      2 -2.849891  2.932414
3413 -0.222845  0.747304      2  1.711359 -0.167621
3414 -0.349423  0.067261      2 -0.126579 -0.680043
3415 -0.402428  0.406218      2 -0.053005  0.338957

[3416 rows x 5 columns]

In [5]:
X_train = df_training.drop(columns=["Class"])
X_train = (X_train - X_train.mean()) / X_train.std() * 100

X_train["Class"] = df_training["Class"]
X_train

            AccX        AccY    DiffAccX    DiffAccY  Class
0      -2.090819    8.424269    0.012037   -0.012577      0
1    -195.187234 -134.475048 -166.006943 -114.501443      0
2     -72.759319   -7.735009  105.272186  101.529709      0
3      85.668834  -21.734057  136.224200  -11.228412      0
4       9.999939  111.070663  -65.045995  106.388643      0
...          ...         ...         ...         ...    ...
3411  106.728131 -257.903714  242.642233 -192.992960      2
3412 -231.948681  129.203106 -291.172960  310.131807      2
3413  -28.573341  107.075511  174.868553  -17.740887      2
3414  -43.615750   17.303333  -12.921013  -71.936747      2
3415  -49.914742   62.048954   -5.403663   35.836967      2

[3416 rows x 5 columns]

In [6]:
X_test = df_test.drop(columns="Class")
X_test = (X_test - X_test.mean()) / X_test.std() * 100

X_test["Class"] = df_test["Class"]
X_test

            AccX        AccY    DiffAccX    DiffAccY  Class
0      67.345100   -9.509000   -0.021340   -0.012385      1
1      57.982946   10.303100   -8.494392   16.758078      1
2     270.452050 -824.010358  192.270076 -706.238535      1
3     229.805029 -828.171460  -36.808209   -3.534656      1
4     283.133326 -732.402479   48.242495   81.053740      1
...          ...         ...         ...         ...    ...
3079  -84.712435  -57.627689  -73.609489   -1.097380      2
3080  145.444037   51.068429  208.277716   91.996249      2
3081  121.268079 -177.287100  -21.901364 -193.309813      2
3082   83.265000   79.069807  -34.415357  216.987532      2
3083  140.063424   35.612446   51.383072  -36.797989      2

[3084 rows x 5 columns]

In [7]:
X_training  = X_train.drop(columns="Class")
y_training  = X_train.Class

X_testing = X_test.drop(columns="Class")
y_testing = X_test.Class

In [8]:
from sklearn.cluster import KMeans
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

In [9]:
kmeans = KMeans(n_clusters=3, random_state=0)
kmeans.fit(X_training)

KMeans(n_clusters=3, random_state=0)

In [10]:
kmeans.labels_

array([1, 0, 2, ..., 2, 0, 2], dtype=int32)

In [11]:
kmeans.score(X_training, y_training)

-77189285.46031395

In [12]:
kmeans.score(X_testing, y_testing)

-76535265.47411464